In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('Data_for_UCI_named.csv')

In [3]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [4]:
df[df['stab']==0]

Empty DataFrame
Columns: [tau1, tau2, tau3, tau4, p1, p2, p3, p4, g1, g2, g3, g4, stab, stabf]
Index: []

In [5]:
df.drop(['stab'],axis=1,inplace=True)

In [6]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  unstable

In [7]:
df.shape

(10000, 13)

In [8]:
from sklearn.model_selection import train_test_split

X = df.drop('stabf',axis=1)

y= df['stabf']

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=1)



In [9]:
x_test.shape

(2000, 12)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

standard_train_df = scaler.fit_transform(x_train)
standard_test_df = scaler.fit_transform(x_test)

In [11]:
standard_train_df = pd.DataFrame(standard_train_df, columns=x_train.columns)
standard_test_df = pd.DataFrame(standard_test_df, columns=x_test.columns)


In [12]:
standard_test_df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  0.592163 -0.420565  1.472472  1.093036  0.426786 -1.504594 -0.792677   
1  0.199183  0.364543 -0.190076 -0.518473 -0.229402 -1.071766  0.427103   
2 -1.086035 -0.321834 -0.873505  0.011761 -0.977094  0.094896  0.813041   
3 -0.087014 -1.113357  0.361518 -1.684316  0.792280 -1.649041  0.410662   
4  0.873004  1.425833  0.080476  1.681022 -0.154247 -0.024315 -0.197525   

         p4        g1        g2        g3        g4  
0  1.600201 -0.925703  1.175287 -1.492644  1.086291  
1  1.052337 -1.655910 -0.395949  1.412703  1.227535  
2  0.751381  1.450284 -1.444370  0.654216 -1.679799  
3 -0.084473  0.066085 -1.679450 -0.349573  1.057439  
4  0.485988  0.119716 -1.475773  0.957057 -0.817608

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
rfc = RandomForestClassifier(random_state = 1)

In [15]:
rfc.fit(x_train,y_train)

RandomForestClassifier(random_state=1)

In [16]:
rfc_pred = rfc.predict(x_test)

In [17]:
from sklearn.metrics import confusion_matrix
cnf_mat = confusion_matrix(y_test,rfc_pred)

In [18]:
good_cnf = pd.DataFrame(cnf_mat, columns=['Actual- Positive', 'Actual- Negative'], 
                        index=['Predicted- Positive', 'Predicted- Negative'])
good_cnf

Actual- Positive  Actual- Negative
Predicted- Positive               625                87
Predicted- Negative                55              1233

In [19]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
precision = precision_score(y_true=y_test, y_pred=rfc_pred, pos_label='unstable')
print('Precision: {}'.format(round(precision*100), 2)) #prints 41.0


Precision: 93.0


In [20]:
recall = recall_score(y_true=y_test, y_pred=rfc_pred, pos_label='stable')
print('Recall: {}'.format(round(recall*100), 2)) #prints 51.0 

Recall: 88.0


In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

      stable       0.92      0.88      0.90       712
    unstable       0.93      0.96      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [22]:
accuracy = accuracy_score(y_true=y_test, y_pred=rfc_pred)
accuracy

0.929

In [23]:
rfc.feature_importances_

array([0.12443249, 0.12630692, 0.12205746, 0.12140145, 0.02913227,
       0.03141126, 0.02995574, 0.02947469, 0.09076479, 0.09768941,
       0.1003254 , 0.09704814])

In [24]:
from sklearn.ensemble import ExtraTreesClassifier
extra_trees = ExtraTreesClassifier(random_state = 1)
extra_trees.fit(x_train,y_train)

ExtraTreesClassifier(random_state=1)

In [25]:
xtra_pred = extra_trees.predict(x_test)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,xtra_pred)

array([[ 606,  106],
       [  38, 1250]], dtype=int64)

In [26]:
accuracy = accuracy_score(y_true=y_test, y_pred=xtra_pred)
accuracy

0.928

In [27]:
from sklearn.metrics import classification_report
print(classification_report(y_test,xtra_pred))

              precision    recall  f1-score   support

      stable       0.94      0.85      0.89       712
    unstable       0.92      0.97      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [28]:
extra_trees.feature_importances_

array([0.11739736, 0.11844468, 0.11316851, 0.11546569, 0.03950675,
       0.04037132, 0.04070628, 0.04057864, 0.08978291, 0.09367636,
       0.09688268, 0.09401882])

In [29]:
n_estimators = [50, 100, 300, 500, 1000]

min_samples_split = [2, 3, 5, 7, 9]

min_samples_leaf = [1, 2, 4, 6, 8]

max_features = ['auto', 'sqrt', 'log2', None] 

hyperparameter_grid = {'n_estimators': n_estimators,

                       'min_samples_leaf': min_samples_leaf,

                       'min_samples_split': min_samples_split,

                       'max_features': max_features}

In [30]:
from sklearn.model_selection import RandomizedSearchCV
#xtra_random = RandomizedSearchCV(extra_trees,hyperparameter_grid, random_state=1)
xtra_random = RandomizedSearchCV(extra_trees, hyperparameter_grid, n_iter = 10, cv = 5, verbose=1, random_state=1)

In [31]:
xtra_random.fit(x_train,y_train)


Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:  3.4min finished


RandomizedSearchCV(cv=5, estimator=ExtraTreesClassifier(random_state=1),
                   param_distributions={'max_features': ['auto', 'sqrt', 'log2',
                                                         None],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 3, 5, 7, 9],
                                        'n_estimators': [50, 100, 300, 500,
                                                         1000]},
                   random_state=1, verbose=1)

In [32]:
xtra_random_pred = xtra_random.predict(x_test)

In [33]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,xtra_random_pred)

array([[ 619,   93],
       [  53, 1235]], dtype=int64)

In [34]:
accuracy = accuracy_score(y_true=y_test, y_pred=xtra_random_pred)
accuracy

0.927

In [35]:
feat_importance= xtra_random.best_estimator_.feature_importances_

In [61]:
pd.DataFrame(feat_importance,index = standard_train_df.columns,columns=['col'])['col'].nlargest

<bound method Series.nlargest of tau1    0.137240
tau2    0.140508
tau3    0.134680
tau4    0.135417
p1      0.003684
p2      0.005337
p3      0.005429
p4      0.004963
g1      0.102562
g2      0.107578
g3      0.113063
g4      0.109541
Name: col, dtype: float64>

In [33]:
from xgboost import XGBClassifier

In [34]:
xgb_model = XGBClassifier(random_state = 1)

In [35]:
xgb_model.fit(x_train,y_train)

XGBClassifier(random_state=1)

In [36]:
xgb_pred = xgb_model.predict(x_test)

In [37]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,xgb_pred)

array([[ 603,  109],
       [  52, 1236]], dtype=int64)

In [46]:
accuracy = accuracy_score(y_true=y_test, y_pred=xgb_pred)
accuracy

0.9195

In [38]:
from lightgbm import LGBMClassifier

In [39]:
lgbm_model = LGBMClassifier(random_state = 1)

In [40]:
lgbm_model.fit(x_train,y_train)

LGBMClassifier(random_state=1)

In [41]:
lgbm_pred = lgbm_model.predict(x_test)

In [42]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,lgbm_pred)

array([[ 636,   76],
       [  49, 1239]], dtype=int64)

In [47]:
accuracy = accuracy_score(y_true=y_test, y_pred=lgbm_pred)
accuracy

0.9375